apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Value.metadata.nameSite }}
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
        role: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:{{ .Values.spec.imageVer }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        # env:
        # - name: DB_NAME 
        #   valueFrom:
        #     configMapKeyRef:
        #       name: config-wp     
        #       key: DB_NAME
        # - name: DB_USER 
        #   valueFrom:
        #     configMapKeyRef:
        #       name: config-wp     
        #       key: DB_USER
        # - name: DB_PASSWORD 
        #   valueFrom:
        #     configMapKeyRef:
        #       name: config-wp     
        #       key: DB_PASSWORD
        # - name: DB_HOST 
        #   valueFrom:
        #     configMapKeyRef:
        #       name: config-wp     
        #       key: DB_HOST
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  selector:
    role: tomcat
  ports:
  - protocol: TCP
    port: {{ .Values.spec.portTomcat }}
    targetPort: {{ .Values.spec.portTomcat }}