apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wp-test
        role: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:fpm-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: DB_NAME 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: DB_NAME
        - name: DB_USER 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: DB_USER
        - name: DB_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: DB_PASSWORD
        - name: DB_HOST 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: DB_HOST
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wp-service
  labels:
    app: wp-test
spec:
  selector:
    role: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80