apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: wp-test
spec:
  type: NodePort
  ports:
  - port: 80
    name: wp-test
    targetPort: 80
    nodePort: 31000
  selector:
    app: wp-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wp-test
        role: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
