nameFront: nginx-test
nameBack: site-test
nameDb: mysql-test
labels:
  app: site

imageFront: nginx:latest
imageBack: bitnami/wordpress:latest
imageDb: mysql:latest
portWp: 80
portDb: 3306
portFront: 31000
replicaCountFront: 2
replicaCountBack: 1
replicaCountDb: 1