nameFront: nginx-test
nameBack: site-test
nameDb: mysql-test
labels:
  app: site

imageFront: nginx:latest
imageBack: bitnami/wordpress:latest
imageDb: mysql:latest
portExt: 8080
portInt: 80
portDb: 3306
portFront: 31000
replicaCountFront: 1
replicaCountBack: 1
replicaCountDb: 1