nameFront: nginx-test
nameBack: site-test
nameDb: mysql-test
labels:
  app: site

imageFront: nginx:latest
imageBack: nginxdemos/hello
imageDb: mysql:latest
portExt: 80
portInt: 80
portDb: 3306
portFront: 31000
replicaCountFront: 1
replicaCountBack: 1
replicaCountDb: 1

limits:
  memoryFront : "128Mi"
  memoryBack  : "128Mi"
  memoryDb    : "400Mi"
  cpuFront    : "200m"
  cpuBack     : "200m"
  cpuDb       : "200m"