metadata:
  nameFront : nginx-test
  nameBack  : site-test
  nameDb    : mysql-test
  labels:
    app: site

image:
  front : nginx:latest
  back  : luzifer/alpine-nginx-php
  db    : mysql:latest

ports:
  web   : 80
  db    : 3306
  front : 31000

replicas:
  front : 1
  back  : 1
  db    : 1

limits:
  memoryFront : "128Mi"
  memoryBack  : "128Mi"
  memoryDb    : "400Mi"
  cpuFront    : "200m"
  cpuBack     : "200m"
  cpuDb       : "200m"


path:
  nginxConf: /etc/nginx/
  nginxLog: /var/log/nginx/
  apacheConf: /usr/local/apache2/conf/
  apacheLog: /var/log/apache/
  siteFiles: /var/www/
