labels:
  app: site

image:
  front : nginx:latest
  back  : nginx-wp:1.2
  db    : mysql:latest
imagePullPolicy: IfNotPresent

replicas:
  front : 1
  back  : 1
  db    : 1

limits:
  memoryFront : "128Mi"
  memoryBack  : "128Mi"
  memoryDb    : "400Mi"
  cpuFront    : "200m"
  cpuBack     : "200m"
  cpuDb       : "200m"


path:
  nginxConf: /etc/nginx/
  nginxLog: /var/log/nginx/
  siteFiles: /var/www/
