apiVersion: v1
kind: pod
metadata:
  name: web
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: mysql
      image: mysql:5.7
    - name: wordpress
      image: wordpress:latest
      