apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: mysql
      image: mysql:5.7
      env:
        - MYSQL_ROOT_PASSWORD:$MYSQL_ROOT_PASSWORD
    - name: wordpress
      image: wordpress:latest
      