apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.nameBack }}
spec:
  replicas: {{ .Values.replicas.back }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
        role: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.back }}
        resources:
          limits:
            memory: {{ .Values.limits.memoryBack }}
            cpu: {{ .Values.limits.cpuBack }}
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/local/apache2/htdocs/
            name: wp-files
      volumes:
        - name: wp-files
          hostPath:
            path: /home/kube/wordpress/
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  selector:
    role: backend
  ports:
  - protocol: TCP
    port: {{ .Values.ports.web }}
    targetPort: 8080