apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.nameDb }}
spec:
  replicas: {{ .Values.replicas.db }}
  selector:
    matchLabels:
      role: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
        role: database
    spec:
      containers:
        - name: mysql
          image: {{ .Values.image.db }}
          resources:
            limits:
              memory: {{ .Values.limits.memoryDb }}
              cpu: {{ .Values.limits.cpuDb }}
          ports:
            - containerPort: {{ .Values.ports.db }}
          env:
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              configMapKeyRef:
                name: config-mysql     
                key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  selector:
    role: database
  ports:
  - protocol: TCP
    port: {{ .Values.ports.db }}
    targetPort: {{ .Values.ports.db }}
