apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicas.back }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.back }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          limits:
            memory: {{ .Values.limits.memoryBack }}
            cpu: {{ .Values.limits.cpuBack }}
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: {{ .Values.replicas.db }}
  selector:
    matchLabels:
      role: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: database
    spec:
      containers:
        - name: mysql
          image: {{ .Values.image.db }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            limits:
              memory: {{ .Values.limits.memoryDb }}
              cpu: {{ .Values.limits.cpuDb }}
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              configMapKeyRef:
                name: config-mysql     
                key: MYSQL_ROOT_PASSWORD