apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameDb }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      role: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: database
    spec:
      containers:
        - name: mysql
          image: {{ .Values.imageDb }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "qwerty123"
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }} -mysql-service
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    role: database
  ports:
  - protocol: TCP
    port: {{ .Values.portDb }}
    targetPort: {{ .Values.portDb }}
