apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameBack }}
spec:
  replicas: {{ .Values.replicaCountBack }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.imageBack }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: DB_NAME 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: WORDPRESS_DATABASE_NAME
        - name: DB_USER 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: WORDPRESS_DATABASE_USER
        - name: DB_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: WORDPRESS_DATABASE_PASSWORD
        - name: DB_HOST 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: WORDPRESS_DATABASE_HOST
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    role: backend
  ports:
  - protocol: TCP
    port: {{ .Values.portWp }}
    targetPort: {{ .Values.portWp }}