apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameBack }}
spec:
  replicas: {{ .Values.replicaCountBack }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.imageBack }}
        resources:
          limits:
            memory: {{ .Values.limits.memoryBack }}
            cpu: {{ .Values.limits.cpuBack }}
        env:
        - name: WORDPRESS_DATABASE_NAME 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: WORDPRESS_DATABASE_NAME
        - name: WORDPRESS_DATABASE_USER 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: WORDPRESS_DATABASE_USER
        - name: WORDPRESS_DATABASE_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: WORDPRESS_DATABASE_PASSWORD
        - name: WORDPRESS_DATABASE_HOST 
          valueFrom:
            configMapKeyRef:
              name: config-wp     
              key: WORDPRESS_DATABASE_HOST
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: config-mysql     
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    role: backend
  ports:
  - protocol: TCP
    port: {{ .Values.portExt }}
    targetPort: {{ .Values.portInt }}