apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.nameBack }}
spec:
  replicas: {{ .Values.replicas.back }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
        role: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.image.back }}
        resources:
          limits:
            memory: {{ .Values.limits.memoryBack }}
            cpu: {{ .Values.limits.cpuBack }}
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: {{ .Values.path.siteFiles }}
            name: wp-files
          - mountPath: {{ .Values.path.apacheConf }}
            name: apache-conf
          - mountPath: {{ .Values.path.apacheLog }}
      volumes:
        - name: wp-files
          hostPath:
            path: /home/kube/wordpress/
        - name: apache-conf
          hostPath: /home/kube/apache/conf/
        - name: apache-log
          hostPath: /home/kube/apache/log/
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  selector:
    role: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80