apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameBack }}
spec:
  replicas: {{ .Values.replicaCountBack }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.imageBack }}
        resources:
          limits:
            memory: {{ .Values.limits.memoryBack }}
            cpu: {{ .Values.limits.cpuBack }}
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: nginx-back
      volumes:
        - name: nginx-back
          hostPath:
            path: /home/kube/nginx-conf/
---
apiVersion: v1
kind: Service
metadata:
  name: site-service
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    role: backend
  ports:
  - protocol: TCP
    port: {{ .Values.portExt }}
    targetPort: {{ .Values.portInt }}