apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameDb }}
spec:
  replicas: {{ .Values.replicaCountDb }}
  selector:
    matchLabels:
      role: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: database
    spec:
      containers:
        - name: mysql
          image: {{ .Values.imageDb }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 3306
          volumes:
          - name: log
            hostPath:
              path: /home/kube/log/mysql
          env:
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              configMapKeyRef:
                name: config-mysql     
                key: MYSQL_ROOT_PASSWORD
          
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    role: database
  ports:
  - protocol: TCP
    port: {{ .Values.portDb }}
    targetPort: {{ .Values.portDb }}
