apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameDb }}
spec:
  replicas: {{ .Values.replicaCountDb }}
  selector:
    matchLabels:
      role: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        role: database
    spec:
      containers:
        - name: mysql
          image: {{ .Values.imageDb }}
          resources:
            limits:
              memory: {{ .Values.limits.memoryDb }}
              cpu: {{ .Values.limits.cpuDb }}
          ports:
            - containerPort: {{ .Values.portDb }}
          env:
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              configMapKeyRef:
                name: config-mysql     
                key: MYSQL_ROOT_PASSWORD
          volumeMounts:
          - mountPath: /var/log/nginx/mysql
            name: log-mysql
      volumes:
        - name: log-mysql
          hostPath:
            path: /home/kube/log/mysql
          
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    role: database
  ports:
  - protocol: TCP
    port: {{ .Values.portDb }}
    targetPort: {{ .Values.portDb }}
