apiVersion: v1
kind: Service
metadata:
  name: backend-service-{{ .Chart.Name }}{{ .Chart.Version }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    role: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-{{ .Chart.Name }}{{ .Chart.Version }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    role: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306